apiVersion: v1
kind: Pod
metadata:
  name: helloworld
spec:
  containers:
  - image: wbira/helloworld:1.2
    name: helloworld
    livenessProbe:
      httpGet:
        path: /healty
        port: 8080
      initialDelaySeconds: 5
      timeoutSeconds: 1
      periodSeconds: 10
      failureThreshold: 3
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
