build-large:
	docker build -t wbira/helloworld:1.0 . -f Dockerfile.large

build-mini:
	docker build -t wbira/helloworld:1.1 . -f Dockerfile.mini

build-optimized:
	docker build -t wbira/helloworld:1.2 . -f Dockerfile.optimized